#!/usr/bin/env ruby

require 'set'
require 'open-uri'

USB_DEVICE_URL = "http://www.linux-usb.org/usb.ids"
PCI_DEVICE_URL = "http://www.pcidatabase.com/reports.php?type=tab-delimeted"

vendors_script = "redef Hardware::vendors += {\n";
devices_script = "redef Hardware::devices += {\n";

v_id = ""
v_name = ""
v_indexes = Set.new
d_indexes = Set.new

open(USB_DEVICE_URL).read.each_line do |line|
	line.chomp!

	# This line indicates a move on to stuff other than usb
	break if line == "# List of known device classes, subclasses and protocols"

	if line =~ /^([0-9a-f]{4})  (.*)$/
		v_id = $1.upcase
		v_name = $2.gsub(/\"/, "\\\"")
		index = "[Hardware::TYPE_USB, \"#{v_id}\"]"
		if ( not v_indexes.include?(index) )
			vendors_script += "	[Hardware::TYPE_USB, \"#{v_id}\"] = \"#{v_name}\",\n"
			v_indexes << index
		end
	elsif ! v_id.empty? && line =~ /^\t([0-9a-f]{4})  (.*)$/
		p_id = $1.upcase
		p_name = $2.gsub(/\"/, "\\\"")
		index = "[Hardware::TYPE_USB, \"#{v_id}\", \"#{p_id}\"]"
		if ( not d_indexes.include?(index) )
			devices_script += "	[Hardware::TYPE_USB, \"#{v_id}\", \"#{p_id}\"] = \"#{p_name}\",\n"
			d_indexes << index
		end
	end
end

v_id = ""
v_name = ""

open(PCI_DEVICE_URL).read.each_line do |line|
	line = line.chomp.force_encoding("ASCII-8BIT")
	if line =~ /^([0-9a-f]{4})\t(.*)$/
		v_id = $1.upcase
		v_name = $2.gsub(/\"/, "\\\"").gsub(/\\/, "\\\\\\")
		index = "[Hardware::TYPE_PCI, \"#{v_id}\"]"
		if ( not v_indexes.include?(index) )
			vendors_script += "	[Hardware::TYPE_PCI, \"#{v_id}\"] = \"#{v_name}\",\n"
			v_indexes << index
		end
	elsif line =~ /^\t([^\t]*)\t(.*)$/
		p_id = $1.upcase
		p_name = $2
		p_name = p_name.gsub(/\"/, "\\\"").gsub(/\\/, "\\\\\\")
		index = "[Hardware::TYPE_PCI, \"#{v_id}\", \"#{p_id}\"]"
		if ( not p_id.empty? and not p_name.empty? and not d_indexes.include?(index) )
			devices_script += "	[Hardware::TYPE_PCI, \"#{v_id}\", \"#{p_id}\"] = \"#{p_name}\",\n"
			d_indexes << index
		end
	end

end
vendors_script += "};\n"
devices_script += "};\n"


puts "# This file was autogenerated, do not edit!"
puts
puts vendors_script
puts devices_script
